create extension if not exists pgcrypto;

create table public.devices (
  id uuid primary key default gen_random_uuid(),
  device_code text not null unique,
  name text not null,
  location text not null,
  device_type text not null,
  status text not null default 'offline',
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  constraint devices_device_code_format check (device_code ~ '^[a-z0-9]+(_[a-z0-9]+)*$'),
  constraint devices_device_type_check check (device_type in ('fridge_probe', 'room_monitor')),
  constraint devices_status_check check (status in ('online', 'offline', 'maintenance', 'disabled'))
);

create table public.readings (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices(id) on delete restrict,
  metric text not null,
  value numeric(10, 3) not null,
  unit text not null,
  quality text not null default 'good',
  recorded_at timestamptz not null,
  received_at timestamptz not null default now(),
  constraint readings_metric_check check (metric in ('temperature', 'humidity', 'smoke', 'detector_alarm')),
  constraint readings_unit_check check (unit in ('celsius', 'percent_rh', 'ppm', 'alarm_state')),
  constraint readings_quality_check check (quality in ('good', 'suspect', 'invalid')),
  constraint readings_metric_unit_check check (
    (metric = 'temperature' and unit = 'celsius')
    or (metric = 'humidity' and unit = 'percent_rh')
    or (metric = 'smoke' and unit = 'ppm')
    or (metric = 'detector_alarm' and unit = 'alarm_state')
  ),
  constraint readings_temperature_range check (metric <> 'temperature' or (value >= -50 and value <= 80)),
  constraint readings_humidity_range check (metric <> 'humidity' or (value >= 0 and value <= 100)),
  constraint readings_smoke_range check (metric <> 'smoke' or value >= 0),
  constraint readings_alarm_state_range check (metric <> 'detector_alarm' or value in (0, 1)),
  constraint readings_recorded_before_received check (recorded_at <= received_at + interval '5 minutes')
);

create table public.alert_rules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  device_id uuid not null references public.devices(id) on delete cascade,
  metric text not null,
  minimum_value numeric(10, 3),
  maximum_value numeric(10, 3),
  duration_seconds integer not null,
  severity text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  constraint alert_rules_device_metric_name_unique unique (device_id, metric, name),
  constraint alert_rules_metric_check check (metric in ('temperature', 'humidity', 'smoke', 'detector_alarm', 'heartbeat')),
  constraint alert_rules_severity_check check (severity in ('warning', 'critical', 'emergency')),
  constraint alert_rules_duration_positive check (duration_seconds > 0),
  constraint alert_rules_has_threshold check (
    metric = 'heartbeat'
    or minimum_value is not null
    or maximum_value is not null
  ),
  constraint alert_rules_threshold_order check (
    minimum_value is null
    or maximum_value is null
    or minimum_value <= maximum_value
  )
);

create table public.alerts (
  id uuid primary key default gen_random_uuid(),
  rule_id uuid not null references public.alert_rules(id) on delete restrict,
  device_id uuid not null references public.devices(id) on delete restrict,
  status text not null default 'active',
  message text not null,
  trigger_value numeric(10, 3),
  triggered_at timestamptz not null,
  acknowledged_at timestamptz,
  acknowledged_by uuid,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  constraint alerts_status_check check (status in ('active', 'acknowledged', 'resolved')),
  constraint alerts_resolved_at_check check (
    (status = 'resolved' and resolved_at is not null)
    or (status <> 'resolved' and resolved_at is null)
  ),
  constraint alerts_acknowledged_at_check check (
    (status = 'acknowledged' and acknowledged_at is not null)
    or status <> 'acknowledged'
  )
);

create index readings_device_metric_recorded_at_idx
  on public.readings (device_id, metric, recorded_at desc);

create unique index if not exists readings_device_metric_recorded_at_unique_idx
  on public.readings (device_id, metric, recorded_at);

create index readings_recorded_at_idx
  on public.readings (recorded_at desc);

create index alert_rules_device_metric_idx
  on public.alert_rules (device_id, metric)
  where enabled;

create index alerts_device_status_triggered_at_idx
  on public.alerts (device_id, status, triggered_at desc);

create unique index alerts_one_open_per_rule_device_idx
  on public.alerts (rule_id, device_id)
  where status in ('active', 'acknowledged');

alter table public.devices enable row level security;
alter table public.readings enable row level security;
alter table public.alert_rules enable row level security;
alter table public.alerts enable row level security;

revoke all on table public.devices from anon, authenticated;
revoke all on table public.readings from anon, authenticated;
revoke all on table public.alert_rules from anon, authenticated;
revoke all on table public.alerts from anon, authenticated;
revoke all on sequence public.readings_id_seq from anon, authenticated;

grant select (id, device_code, name, location, device_type, status, last_seen_at, created_at)
  on table public.devices to anon;
grant select (id, device_id, metric, value, unit, quality, recorded_at, received_at)
  on table public.readings to anon;
grant select (id, name, device_id, metric, minimum_value, maximum_value, duration_seconds, severity, enabled)
  on table public.alert_rules to anon;
grant select (id, rule_id, device_id, status, message, trigger_value, triggered_at, acknowledged_at, resolved_at)
  on table public.alerts to anon;

grant all on table public.devices to service_role;
grant all on table public.readings to service_role;
grant all on table public.alert_rules to service_role;
grant all on table public.alerts to service_role;
grant usage, select on sequence public.readings_id_seq to service_role;

create policy "public dashboard can read devices"
  on public.devices for select
  to anon
  using (true);

create policy "public dashboard can read readings"
  on public.readings for select
  to anon
  using (true);

create policy "public dashboard can read alert rules"
  on public.alert_rules for select
  to anon
  using (true);

create policy "public dashboard can read alerts"
  on public.alerts for select
  to anon
  using (true);
